apiVersion: apps/v1
kind: Deployment
metadata:
  name: condus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: condus-amazing-race-app
      component: frontend
  template:
    metadata:
      labels:
        app: condus-amazing-race-app
        component: frontend
    spec:
      containers:
      - name: condus-frontend
        image: FRONTEND/IMAGE
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
