apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ohtuprojekti-staging

resources:
- secret.yaml
- imagestream.yaml
- ../../base

patches:
- path: deployment-patch.yaml
- path: route-patch.yaml