apiVersion: v1
kind: Secret
metadata:
    name: condus-db-secret
data:
    API_KEY: ENC[AES256_GCM,data:1a03guB/v3s4qlbU3hKLxSvCx7H5KTzOH76igd+xPZv4Ctotobqs/ZqgxLAT9GIxrjYUvzouPRkH26+2yJzIOayXY2DkEAucRj4J/kXzUgV1F7ZaL8ogkzBsshYdiq7v4XqWqVi4/+TqRhQYWtokDJE1zbLQ8uh41aH4bBM9PoBefBeysdCTsH+MhpogQroqGYNdLJp17XepDh+cg+Lvy3+/AaKEiVrm8Vhil+QKrCT7ff51WkcxKB01Wd3sZrf4jY5SMo3yPwVCN6dYZW0/JgvZ2eHwdsYtxC/L2zyuNK+bD+EdZb77F4GY8LH3c51kTE5GJNcYtnoJqUBmZXUsqXeBO6XYo24wG0pVlLxsqe/D3vWVUJFYpbf4ZN48GDsdvqPzCGkChnISzSXvBF+OYr6O95QvJEJVSZFaXs4ndmBDhglAikojNnnzwPI50qZnqDlUi+VkP9YYBktt27ovvrb2Q+3AGAmvp3XS8skdMqz4rbgEJ5DKQNZQ2YGAKAw=,iv:ONLoY4/+bO9Pyn8F36wjX7FWDmSv5Vav+lMKp5HvoME=,tag:oKyo0th6j46F8A2sBJ3ZXg==,type:str]
sops:
    age:
        - recipient: age1qfyppd3radnltf33a2t9n4m6u9sswh87zctfzjavje9alf6ayq3qysdp6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL20wbVRSTzlwd0ZTSDZn
            Nnk3cEZhdGlISkNTcGEveUl0SWZBcGNPRzBjCjBWVkphak1pdmJOOUF6MDNtMkZp
            MHdKelc4L3ZybHY2OUhxRzAveG1hVWMKLS0tIFVodVRFNFVQOE5IMWdieHBQMlNo
            YkR4RHV3NGwrMGFHT0g3ZDhyaUViSXMK90TlCddz47pAmQ5J3n+zu4Wg/BTwRH6n
            ikov18xcrOQneBgeMkAG9zXtk2tNnSjNRxjtCxH9VvvQ+dOn/P7U0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T08:18:00Z"
    mac: ENC[AES256_GCM,data:mHwbfz1+QtgOonwujh4qPPLUkzmzIRC81ttAUCfXfbVUd23ih09OvUXuzNpH0Z4Qujh6bK1vtqqJn9CLKevzaheIhAUgGrahYwk5HgU4ddWHyqkXi4G/zpn0p4q6K4uP+ANKkaBEXcmb+KMKb8sSE2g9umOiTG44ZgPDDFtqp6I=,iv:RDdiyWY9O38BuD+UT+ZbxG8PoCGA1ZMQ2NhXoZBKiTQ=,tag:xQA077f8ILLHFrsgVBIOAg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
