name: "backend pipeline"

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
         node-version: "latest"
    - name: Install dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint

  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Print todo
      run:
        echo "todo"