name: "backend pipeline"

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
         node-version: "latest"
    - name: Install dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint

  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Print todo
      run:
        echo "todo"

  build-and-push-image:
    if: github.ref == 'refs/heads/main'
    needs: [lint, test]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/amazing-race-condus/condus-backend:latest
            ghcr.io/amazing-race-condus/condus-backend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/amazing-race-condus/condus-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/amazing-race-condus/condus-backend:buildcache,mode=max