name: "backend pipeline"

on:
  workflow_call:
    secrets:
      DATABASE_URL:
        required: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: "npm"
        cache-dependency-path: backend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint

  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: "npm"
        cache-dependency-path: backend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Generate prisma
      run: npx prisma generate
    - name: Run tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npm run test
