  name: CI/CD pipeline

  on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - 'backend/**'
    pull_request:
      branches:
        - 'main'
        - 'dev'
      paths:
        - 'frontend/**'
        - 'backend/**'

  jobs:
    frontend:
      uses: ./.github/workflows/frontend.yaml

    backend:
      uses: ./.github/workflows/backend.yaml
      secrets:
        SECRET: ${{ secrets.SECRET }}

    build-and-push-image:
      if: |
        always()
        && github.ref == 'refs/heads/main'
      needs: [frontend, backend]
      runs-on: ubuntu-24.04
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4
        - name: log in to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Setup buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
              ghcr.io/amazing-race-condus/condus-amazing-race:latest
              ghcr.io/amazing-race-condus/condus-amazing-race:${{ github.sha }}
            cache-from: type=registry,ref=ghcr.io/amazing-race-condus/condus-amazing-race:buildcache
            cache-to: type=registry,ref=ghcr.io/amazing-race-condus/condus-amazing-race:buildcache,mode=max
