  name: CI/CD pipeline

  on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - 'backend/**'
    pull_request:
      branches:
        - 'main'
      paths:
        - 'frontend/**'
        - 'backend/**'

  jobs:
    paths-filter:
      runs-on: ubuntu-24.04
      outputs:
        frontend: ${{ steps.filter.outputs.frontend }}
        backend: ${{ steps.filter.outputs.backend }}
      steps:
        - uses: actions/checkout@v4
        - name: Filter changed paths
          id: filter
          uses: dorny/paths-filter@v3
          with:
            filters: |
              frontend:
                - 'frontend/**'
              backend:
                - 'backend/**'

    frontend:
      needs: [paths-filter]
      if: ${{ needs.paths-filter.outputs.frontend == 'true' }}
      uses: ./.github/workflows/frontend.yaml

    backend:
      needs: [paths-filter]
      if: ${{ needs.paths-filter.outputs.backend == 'true' }}
      uses: ./.github/workflows/backend.yaml
