  name: CI/CD pipeline

  on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - 'backend/**'
    pull_request:
      branches:
        - 'main'
      paths:
        - 'frontend/**'
        - 'backend/**'

  jobs:
    # paths-filter:
    #   runs-on: ubuntu-24.04
    #   outputs:
    #     frontend: ${{ steps.filter.outputs.frontend }}
    #     backend: ${{ steps.filter.outputs.backend }}
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Filter changed paths
    #       id: filter
    #       uses: dorny/paths-filter@v3
    #       with:
    #         filters: |
    #           frontend:
    #             - 'frontend/**'
    #           backend:
    #             - 'backend/**'

    frontend:
      # needs: [paths-filter]
      # if: ${{ needs.paths-filter.outputs.frontend == 'true' }}
      uses: ./.github/workflows/frontend.yaml

    backend:
      # needs: [paths-filter]
      # if: ${{ needs.paths-filter.outputs.backend == 'true' }}
      uses: ./.github/workflows/backend.yaml

      # && (
      #   (needs.paths-filter.outputs.frontend == 'true' ||
      #   needs.paths-filter.outputs.backend == 'true') &&
      #   (needs.frontend.result == 'success' || needs.frontend.result == 'skipped') &&
      #   (needs.backend.result == 'success' || needs.backend.result == 'skipped')
      # )
    build-and-push-image:
      if: |
        always()
        && github.ref == 'refs/heads/main'
      needs: [frontend, backend]
      runs-on: ubuntu-24.04
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4
        - name: log in to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Setup buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
              ghcr.io/amazing-race-condus/condus-amazing-race:latest
              ghcr.io/amazing-race-condus/condus-amazing-race:${{ github.sha }}
            cache-from: type=registry,ref=ghcr.io/amazing-race-condus/condus-amazing-race:buildcache
            cache-to: type=registry,ref=ghcr.io/amazing-race-condus/condus-amazing-race:buildcache,mode=max
